<?php

/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="page-header">
    <h1>Search houses</h1>
    <p><?php echo $this->tag->linkTo(["/houses/new", "Create houses"]) ?></p>
</div>

<?php echo $this->getContent() ?>

<?php echo $this->flash->output() ?>

<form action="/houses/search" class="form-horizontal" method="get">
    <div class="form-group">
        <label for="fieldId" class="col-sm-2 control-label">Id</label>
        <div class="col-sm-10">
            <?php echo $this->tag->textField(["id", "size" => 30, "class" => "form-control", "id" => "fieldId"]); ?>
        </div>
    </div>

    <div class="form-group">
        <label for="fieldStreet" class="col-sm-2 control-label">Street</label>
        <div class="col-sm-10">
            <?php echo $this->tag->textField(["street", "size" => 30, "class" => "form-control", "id" => "fieldStreet"]); ?>
        </div>
    </div>

    <div class="form-group">
        <label for="fieldNumber" class="col-sm-2 control-label">Number</label>
        <div class="col-sm-10">
            <?php echo $this->tag->textField(["number", "size" => 30, "class" => "form-control", "id" => "fieldNumber"]); ?>
        </div>
    </div>

    <div class="form-group">
        <label for="fieldAddition" class="col-sm-2 control-label">Addition</label>
        <div class="col-sm-10">
            <?php echo $this->tag->textField(["addition", "size" => 30, "class" => "form-control", "id" => "fieldAddition"]); ?>
        </div>
    </div>

    <div class="form-group">
        <label for="fieldZipcode" class="col-sm-2 control-label">ZipCode</label>
        <div class="col-sm-10">
            <?php echo $this->tag->textField(["zipCode", "size" => 30, "class" => "form-control", "id" => "fieldZipcode"]); ?>
        </div>
    </div>

    <div class="form-group">
        <label for="fieldCity" class="col-sm-2 control-label">City</label>
        <div class="col-sm-10">
            <?php echo $this->tag->textField(["city", "size" => 30, "class" => "form-control", "id" => "fieldCity"]); ?>
        </div>
    </div>

    <div class="form-group">
        <label for="fieldRooms" class="col-sm-2 control-label">Rooms</label>
        <div class="col-sm-10">
            <?php echo $this->tag->textField(["rooms", "size" => 30, "class" => "form-control", "id" => "fieldRooms"]); ?>
        </div>
    </div>


    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <?php echo $this->tag->submitButton(["Search", "class" => "btn btn-default"]) ?>
        </div>
    </div>
</form>