<?php

/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(["houses/index", "Go Back"]); ?></li>
            <li class="next"><?php echo $this->tag->linkTo(["houses/new", "Create "]); ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>Search result</h1>
</div>

<?php echo $this->getContent(); ?>

<div class="row">
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>Id</th>
                <th>Street</th>
                <th>Number</th>
                <th>Addition</th>
                <th>ZipCode</th>
                <th>City</th>
                <th>Rooms</th>

                <th></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($page->getItems() as $house) : ?>
                <tr>
                    <td><?php echo $house["id"]; ?></td>
                    <td><?php echo $house["street"]; ?></td>
                    <td><?php echo $house["number"]; ?></td>
                    <td><?php echo $house["addition"]; ?></td>
                    <td><?php echo $house["zipCode"]; ?></td>
                    <td><?php echo $house["city"]; ?></td>
                    <!-- TODO: zorgen dat er in plaats van rooms en foreach loop komt die uit de room db alles haalt -->
                    <td><?php echo $house["rooms"]; ?></td>

                    <td><?php echo $this->tag->linkTo(["/houses/edit/" . $house['id'], "Edit"]); ?></td>
                    <td><?php echo $this->tag->linkTo(["/houses/delete/" . $house['id'], "Delete"]); ?></td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
</div>

<div class="row">
    <div class="col-sm-1">
        <p class="pagination" style="line-height: 1.42857;padding: 6px 12px;">
            <?php echo $page->getCurrent(), "/", $page->getTotalItems() ?>
        </p>
    </div>
    <div class="col-sm-11">
        <nav>
            <ul class="pagination">
                <li><?php echo $this->tag->linkTo(["/houses/search", "First", 'class' => 'page-link', 'id' => 'first']) ?></li>
                <li><?php echo $this->tag->linkTo(["/houses/search?page=" . $page->getPrevious(), "Previous", 'class' => 'page-link', 'id' => 'previous']) ?></li>
                <li><?php echo $this->tag->linkTo(["/houses/search?page=" . $page->getNext(), "Next", 'class' => 'page-link', 'id' => 'next']) ?></li>
                <li><?php echo $this->tag->linkTo(["/houses/search?page=" . $page->getLast(), "Last", 'class' => 'page-link', 'id' => 'last']) ?></li>
            </ul>
        </nav>
    </div>
</div>