<?php

/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(["user", "Go Back"]) ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>register</h1>
</div>

<?php echo $this->getContent(); ?>

<form action="/user/create" class="form-horizontal" method="post">
    <div class="form-group">
        <label for="fieldUsername" class="col-sm-2 control-label">Username</label>
        <div class="col-sm-10">
            <?php echo $this->tag->textField(["username", "size" => 30, "class" => "form-control", "id" => "fieldUsername"]); ?>
        </div>
    </div>

    <div class="form-group">
        <label for="fieldPassword" class="col-sm-2 control-label">Password</label>
        <div class="col-sm-10">
            <?php echo $this->tag->passwordField(["password", "size" => 30, "class" => "form-control", "id" => "fieldPassword"]); ?>
        </div>
    </div>

    <div class="form-group">
        <label for="fieldFirstname" class="col-sm-2 control-label">Firstname</label>
        <div class="col-sm-10">
            <?php echo $this->tag->textField(["firstname", "size" => 30, "class" => "form-control", "id" => "fieldFirstname"]); ?>
        </div>
    </div>

    <div class="form-group">
        <label for="fieldSurname" class="col-sm-2 control-label">Surname</label>
        <div class="col-sm-10">
            <?php echo $this->tag->textField(["surname", "size" => 30, "class" => "form-control", "id" => "fieldSurname"]); ?>
        </div>
    </div>

    <div class="form-group">
        <label for="fieldEmailaddress" class="col-sm-2 control-label">EmailAddress</label>
        <div class="col-sm-10">
            <?php echo $this->tag->emailField(["emailAddress", "size" => 30, "class" => "form-control", "id" => "fieldEmailaddress"]); ?>
        </div>
    </div>
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <?php echo $this->tag->submitButton(["Save", "class" => "btn btn-default"]) ?>
        </div>
    </div>
</form>
<button class="btn  btn-default"><a href="/user/login">login</a></button>