<?php

/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(["/user/index", "Go Back"]); ?></li>
            <li class="next"><?php echo $this->tag->linkTo(["/user/new", "Create "]); ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>Search result</h1>
</div>

<?php echo $this->getContent(); ?>

<div class="row">
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>Id</th>
                <th>Username</th>
                <th>Password</th>
                <th>Firstname</th>
                <th>Surname</th>
                <th>EmailAddress</th>
                <th>Role</th>
                <th>Validationkey</th>
                <th>Status</th>
                <th>Createdat</th>
                <th>Updatedat</th>

                <th></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($page->getItems() as $user) : ?>
                <tr>
                    <td><?php echo $user->getId(); ?></td>
                    <td><?php echo $user->getUsername(); ?></td>
                    <td><?php echo $user->getPassword(); ?></td>
                    <td><?php echo $user->getFirstname(); ?></td>
                    <td><?php echo $user->getSurname(); ?></td>
                    <td><?php echo $user->getEmailaddress(); ?></td>
                    <td><?php echo $user->getRole(); ?></td>
                    <td><?php echo $user->getValidationkey(); ?></td>
                    <td><?php echo $user->getStatus(); ?></td>
                    <td><?php echo $user->getCreatedat(); ?></td>
                    <td><?php echo $user->getUpdatedat(); ?></td>

                    <td><?php echo $this->tag->linkTo(["/user/edit/" . $user['id'], "Edit"]); ?></td>
                    <td><?php echo $this->tag->linkTo(["/user/delete/" . $user['id'], "Delete"]); ?></td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
</div>

<div class="row">
    <div class="col-sm-1">
        <p class="pagination" style="line-height: 1.42857;padding: 6px 12px;">
            <?php echo $page->getCurrent(), "/", $page->getTotalItems() ?>
        </p>
    </div>
    <div class="col-sm-11">
        <nav>
            <ul class="pagination">
                <li><?php echo $this->tag->linkTo(["/user/search", "First", 'class' => 'page-link', 'id' => 'first']) ?></li>
                <li><?php echo $this->tag->linkTo(["/user/search?page=" . $page->getPrevious(), "Previous", 'class' => 'page-link', 'id' => 'previous']) ?></li>
                <li><?php echo $this->tag->linkTo(["/user/search?page=" . $page->getNext(), "Next", 'class' => 'page-link', 'id' => 'next']) ?></li>
                <li><?php echo $this->tag->linkTo(["/user/search?page=" . $page->getLast(), "Last", 'class' => 'page-link', 'id' => 'last']) ?></li>
            </ul>
        </nav>
    </div>
</div>